NUM_PLAYERS = 4

# BOARD_WIDTH = 170
# BOARD_WIDTH = 17
BOARD_WIDTH = 15
# BOARD_HEIGHT = 150
BOARD_HEIGHT = 15
# BLOCK_SIZE = 10 # 1 block = 10*10 board unit
# TILE_HEIGHT = BOARD_WIDTH / BLOCK_SIZE
# TILE_WIDTH = BOARD_HEIGHT / BLOCK_SIZE

ROUND_INTERVAL = 50 # 50 ms
